# Generated by Django 4.1.3 on 2023-01-05 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_user',
            field=models.ManyToManyField(through='news.SubscribersUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
